languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Sunner"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Aloha and welcome to my website!"

[params.author]
  name = "Sunner"
  image = "img/buizel.png"
  headline = "Aloha and welcome to my website!"
  bio = "Software developer and (former) YouTuber from Germany 🇩🇪"
  links = [
     { github = "https://github.com/SuNNjek" },
     { bluesky = "https://bsky.app/profile/sunnjek.de" },
     { mastodon = "https://mastodon.social/@sunnjek" },
     { youtube = "https://youtube.com/@SunnerLP" },
     { twitch = "https://twitch.tv/SunnerLP" },
  ]
